CREATE TABLE ROLES (
  id int(10) NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);

CREATE TABLE USERS (
  id int(10) NOT NULL AUTO_INCREMENT,
  first_name varchar(100) NOT NULL,
  last_name varchar(100) NOT NULL,
  email varchar(100) NOT NULL,
  phone varchar(100) NOT NULL,
  password varchar(100) NOT NULL,
  roles_id int(10) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE PLACES (
  id int(10) NOT NULL AUTO_INCREMENT,
  description varchar(100),
  users_id int(10) NOT NULL,
  place_types_id int(10) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE PLACE_TYPES (
  id int(10) NOT NULL AUTO_INCREMENT,
  type varchar(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE FOOD (
  id int(10) NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  places_id int(10) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE EVENTS (
  id int(10) NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  `date` date NOT NULL,
  places_id int(10) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE RESERVATIONS (
  id int(10) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  num_of_people int(10) NOT NULL,
  users_id int(10) NOT NULL,
  places_id int(10) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE SYSTEM_LOG (
  id int(10) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  description varchar(100) NOT NULL,
  users_id int(10) NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE
  USERS
ADD
  CONSTRAINT FKUSERS210094 FOREIGN KEY (roles_id) REFERENCES ROLES (id);

ALTER TABLE
  PLACES
ADD
  CONSTRAINT FKPLACES531630 FOREIGN KEY (users_id) REFERENCES USERS (id);

ALTER TABLE
  PLACES
ADD
  CONSTRAINT FKPLACES809652 FOREIGN KEY (place_types_id) REFERENCES PLACE_TYPES (id);

ALTER TABLE
  FOOD
ADD
  CONSTRAINT FKFOOD309043 FOREIGN KEY (places_id) REFERENCES PLACES (id);

ALTER TABLE
  EVENTS
ADD
  CONSTRAINT FKEVENTS856849 FOREIGN KEY (places_id) REFERENCES PLACES (id);

ALTER TABLE
  RESERVATIONS
ADD
  CONSTRAINT FKRESERVATIO302475 FOREIGN KEY (users_id) REFERENCES USERS (id);

ALTER TABLE
  RESERVATIONS
ADD
  CONSTRAINT FKRESERVATIO532812 FOREIGN KEY (places_id) REFERENCES PLACES (id);

ALTER TABLE
  SYSTEM_LOG
ADD
  CONSTRAINT FKSYSTEM_LOG170191 FOREIGN KEY (users_id) REFERENCES USERS (id);